In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
import statsmodels.api as sm

In [27]:
fr_cuttle_fish = {'Year': ['1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022'],
        'Quantity': [33845,31778,37258,34589,32799,33677,30568,41381,39610,44239,49651,55701,45955,50750,63504,
59159,54671,63296,68577,82353,65596,63320,69183,60210,70906,59292,58992],
        'Price': [260.86,272.37,323.41,273.31,286.22,288.99,280.07,417.09,435.17,474.01,549.15,797.37,744.13,761.05,923.83,1104.57,1346.72,1354.28,1386.98,1833.21,1636.11,1944.5,2356.46,1975.97,2009.79,1626.34,2062.63]}
df4=pd.DataFrame(fr_cuttle_fish)

In [24]:
p = range(0, 3)  # Autoregressive order
d = range(1, 3)  # Degree of differencing
q = range(0, 3)  # Moving average order

In [5]:
data = pd.Series(fr_cuttle_fish)

In [6]:
pdq_combinations = list(itertools.product(p, d, q))

In [29]:
#  3 rd objectieve forecasting  crtted

In [ ]:
fr_cuttle_fish = {'Year': ['1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022'],
        'Quantity': [33845,31778,37258,34589,32799,33677,30568,41381,39610,44239,49651,55701,45955,50750,63504,
59159,54671,63296,68577,82353,65596,63320,69183,60210,70906,59292,58992],
        'Price': [260.86,272.37,323.41,273.31,286.22,288.99,280.07,417.09,435.17,474.01,549.15,797.37,744.13,761.05,923.83,1104.57,1346.72,1354.28,1386.98,1833.21,1636.11,1944.5,2356.46,1975.97,2009.79,1626.34,2062.63]}
df4=pd.DataFrame(fr_cuttle_fish)

In [28]:
import pandas as pd
import statsmodels.api as sm

# Assuming your data is stored in a dataframe 'df'
# with columns: 'year', 'quantity', 'price'


# Assuming your year data is stored in a column named 'year' in a dataframe 'df'

df4.set_index('Year', inplace=True)



# Extract the 'price' column for forecasting
price_data = df4['Price']

# Fit the ARIMA model
model = sm.tsa.ARIMA(price_data, order=(1,1,0))
model_fit = model.fit()

# Generate forecasts for the next 10 years
forecast = model_fit.forecast(steps=10)

# Print the forecasted values
print(forecast)

(array([1987.98563588, 2107.322598  , 2153.01261529, 2226.66342957,
       2289.69864845, 2356.76418398, 2422.2995696 , 2488.4158919 ,
       2554.3116558 , 2620.29115689]), array([189.11245039, 222.54459968, 265.38171487, 297.39451991,
       327.9173034 , 355.2549265 , 380.83787387, 404.73440889,
       427.32279851, 448.76620792]), array([[1617.33204408, 2358.63922768],
       [1671.14319768, 2543.50199832],
       [1632.87401198, 2673.15121859],
       [1643.78088134, 2809.54597779],
       [1646.99254387, 2932.40475302],
       [1660.47732271, 3053.05104524],
       [1675.87105287, 3168.72808634],
       [1695.15102718, 3281.68075663],
       [1716.77436094, 3391.84895066],
       [1740.7255519 , 3499.85676188]]))

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency AS-JAN will be used.
  warnings.warn('No frequency information was'
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency AS-JAN will be used.
  warnings.warn('No frequency information was'

In [30]:
frozenshrimp = {'Year':['1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022'],
'Quantity': [95724,105427,101318,102484,110275,111874,127709,134815,129768,138085,145180,137397,136223,126039,130553,151465,189125,228620,301435,357505,373866,434486,565980,614145,652253,590275,728123],
'Price':[2356.81,2701.76,3140.56,3344.91,3645.22,4481.51,4139.92,4608.31,4013.07,4220.67,4271.51,4506.08,3941.62,3779.8,4182.35,5718.13,8175.26,9706.36,19368.3,22468.12,20045.5,24711.32,30868.17,31800.51,34152.03,32525.29,42706.04]}

In [31]:
df1=pd.DataFrame(frozenshrimp)

In [33]:
print(" Item : Frozen Shrimp")
df1

 Item : Frozen Shrimp

    Year  Quantity     Price
0   1996     95724   2356.81
1   1997    105427   2701.76
2   1998    101318   3140.56
3   1999    102484   3344.91
4   2000    110275   3645.22
5   2001    111874   4481.51
6   2002    127709   4139.92
7   2003    134815   4608.31
8   2004    129768   4013.07
9   2005    138085   4220.67
10  2006    145180   4271.51
11  2007    137397   4506.08
12  2008    136223   3941.62
13  2009    126039   3779.80
14  2010    130553   4182.35
15  2011    151465   5718.13
16  2012    189125   8175.26
17  2013    228620   9706.36
18  2014    301435  19368.30
19  2015    357505  22468.12
20  2016    373866  20045.50
21  2017    434486  24711.32
22  2018    565980  30868.17
23  2019    614145  31800.51
24  2020    652253  34152.03
25  2021    590275  32525.29
26  2022    728123  42706.04

In [35]:
# to check the stationarity
from statsmodels.tsa.stattools import adfuller
price_column = df1['Price']
result=adfuller(price_column)
adf_statistics = result[0]
p_value = result[1]

In [36]:
print(f'ADF Statistics: {adf_statistics}')
print(f'p_value: {p_value}')

ADF Statistics: 2.507490270798757
p_value: 0.9990522260777142

In [37]:
# result
significance_level =0.05
if p_value < significance_level:
    print("The time series is stationary (reject the null hypothesis).")
else:
    print("The time series is non-stationary (fail to reject the null hypothesis).")

The time series is non-stationary (fail to reject the null hypothesis).

In [38]:
df1['adj_log'] = np.log(df1['Price'])
df1['adj_sqrt'] = np.sqrt(df1['Price'])
df1['adj_cbrt'] = np.cbrt(df1['Price'])

In [39]:
df1 = df1.dropna()
df1

    Year  Quantity     Price    adj_log    adj_sqrt   adj_cbrt
0   1996     95724   2356.81   7.765064   48.546988  13.307859
1   1997    105427   2701.76   7.901659   51.978457  13.927791
2   1998    101318   3140.56   8.052156   56.040699  14.644314
3   1999    102484   3344.91   8.115195   57.835197  14.955289
4   2000    110275   3645.22   8.201172   60.375657  15.390093
5   2001    111874   4481.51   8.407715   66.944081  16.486993
6   2002    127709   4139.92   8.328432   64.342210  16.056984
7   2003    134815   4608.31   8.435616   67.884534  16.641044
8   2004    129768   4013.07   8.297312   63.348796  15.891281
9   2005    138085   4220.67   8.347749   64.966684  16.160711
10  2006    145180   4271.51   8.359723   65.356790  16.225340
11  2007    137397   4506.08   8.413183   67.127342  16.517068
12  2008    136223   3941.62   8.279347   62.782322  15.796405
13  2009    126039   3779.80   8.237426   61.480078  15.577208
14  2010    130553   4182.35   8.338629   64.671091  16.111654
15  2011    151465   5718.13   8.651397   75.618318  17.882079
16  2012    189125   8175.26   9.008868   90.417144  20.144996
17  2013    228620   9706.36   9.180537   98.520861  21.331372
18  2014    301435  19368.30   9.871393  139.170040  26.855330
19  2015    357505  22468.12  10.019853  149.893696  28.217741
20  2016    373866  20045.50   9.905760  141.582132  27.164745
21  2017    434486  24711.32  10.115017  157.198346  29.127194
22  2018    565980  30868.17  10.337481  175.693398  31.369213
23  2019    614145  31800.51  10.367238  178.326975  31.681910
24  2020    652253  34152.03  10.438577  184.802679  32.444332
25  2021    590275  32525.29  10.389773  180.347692  31.920797
26  2022    728123  42706.04  10.662096  206.654397  34.953964

In [40]:
df1['Price_log_diff'] = df1['adj_log'] - df1['adj_log'].shift(1)

In [46]:
df1 = df1.dropna()
df1

      Quantity     Price    adj_log    adj_sqrt   adj_cbrt  Price_log_diff
Year
1997    105427   2701.76   7.901659   51.978457  13.927791        0.136594
1998    101318   3140.56   8.052156   56.040699  14.644314        0.150498
1999    102484   3344.91   8.115195   57.835197  14.955289        0.063039
2000    110275   3645.22   8.201172   60.375657  15.390093        0.085977
2001    111874   4481.51   8.407715   66.944081  16.486993        0.206543
2002    127709   4139.92   8.328432   64.342210  16.056984       -0.079284
2003    134815   4608.31   8.435616   67.884534  16.641044        0.107185
2004    129768   4013.07   8.297312   63.348796  15.891281       -0.138305
2005    138085   4220.67   8.347749   64.966684  16.160711        0.050437
2006    145180   4271.51   8.359723   65.356790  16.225340        0.011974
2007    137397   4506.08   8.413183   67.127342  16.517068        0.053460
2008    136223   3941.62   8.279347   62.782322  15.796405       -0.133836
2009    126039   3779.80   8.237426   61.480078  15.577208       -0.041921
2010    130553   4182.35   8.338629   64.671091  16.111654        0.101202
2011    151465   5718.13   8.651397   75.618318  17.882079        0.312769
2012    189125   8175.26   9.008868   90.417144  20.144996        0.357471
2013    228620   9706.36   9.180537   98.520861  21.331372        0.171669
2014    301435  19368.30   9.871393  139.170040  26.855330        0.690856
2015    357505  22468.12  10.019853  149.893696  28.217741        0.148460
2016    373866  20045.50   9.905760  141.582132  27.164745       -0.114093
2017    434486  24711.32  10.115017  157.198346  29.127194        0.209257
2018    565980  30868.17  10.337481  175.693398  31.369213        0.222464
2019    614145  31800.51  10.367238  178.326975  31.681910        0.029757
2020    652253  34152.03  10.438577  184.802679  32.444332        0.071340
2021    590275  32525.29  10.389773  180.347692  31.920797       -0.048804
2022    728123  42706.04  10.662096  206.654397  34.953964        0.272322

In [47]:
# again checking the stationarity  after  log transformation

from statsmodels.tsa.stattools import adfuller
price_column = df1['Price_log_diff']
result=adfuller(price_column)
adf_statistics = result[0]
p_value = result[1]
print(f'ADF Statistics: {adf_statistics}')
print(f'p_value: {p_value}')
# result
significance_level = 0.05
if p_value < significance_level :
    print("The time series is  stationary (reject the null hypothesis).")
else:
    print("The time series is non-stationary (fail to reject the null hypothesis).")

ADF Statistics: -3.9344797345141225
p_value: 0.0017952506591847354
The time series is  stationary (reject the null hypothesis).

In [49]:
import pandas as pd
import statsmodels.api as sm


# Extract the 'price' column for forecasting
price_data = df1['Price_log_diff']

# Fit the ARIMA model
model = sm.tsa.ARIMA(price_data, order=(1,1,0))
model_fit = model.fit()

# Generate forecasts for the next 10 years
forecast = model_fit.forecast(steps=10)

# Print the forecasted values
print(forecast)

(array([0.13287443, 0.19624973, 0.17030769, 0.18369835, 0.17976806,
       0.18346539, 0.18380375, 0.1856213 , 0.18678746, 0.18824048]), array([0.20293972, 0.23255736, 0.27833327, 0.30960547, 0.34112998,
       0.36869002, 0.39485592, 0.41917329, 0.4422467 , 0.4641362 ]), array([[-0.26488011,  0.53062897],
       [-0.25955433,  0.65205379],
       [-0.37521549,  0.71583087],
       [-0.42311722,  0.79051391],
       [-0.48883442,  0.84837053],
       [-0.53915376,  0.90608455],
       [-0.59009964,  0.95770714],
       [-0.63594325,  1.00718586],
       [-0.68000013,  1.05357506],
       [-0.72144976,  1.09793071]]))

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\arima_model.py:472: FutureWarning:
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been deprecated in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and
statsmodels.tsa.SARIMAX. These will be removed after the 0.12 release.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained.

To silence this warning and continue using ARMA and ARIMA until they are
removed, use:

import warnings
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARMA',
                        FutureWarning)
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARIMA',
                        FutureWarning)

  warnings.warn(ARIMA_DEPRECATION_WARN, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency AS-JAN will be used.
  warnings.warn('No frequency information was'
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency AS-JAN will be used.
  warnings.warn('No frequency information was'

In [52]:
forecast_1=np.exp(forecast[0])

In [53]:
final_forecasted_value = 1000*forecast_1

In [55]:
final_forecasted_value

array([1142.10657832, 1216.8307423 , 1185.66961542, 1201.65328464,
       1196.93970788, 1201.3733897 , 1201.77995269, 1203.96623718,
       1205.37107262, 1207.1237661 ])